export const supportTypes = [
    { rule: /\.(bi)$/i, logo: 'fi-bi' },
    { rule: /\.(sql)$/i, logo: 'fi-spark' },
    { rule: /\.(hql)$/i, logo: 'fi-hive' },
    { rule: /\.(out)$/i, logo: 'fi-storage' },
    { rule: /\.scala$/i, logo: 'fi-scala' },
    { rule: /\.jdbc$/i, logo: 'fi-jdbc' },
    { rule: /\.python$/i, logo: 'fi-python' },
    { rule: /\.py$/i, logo: 'fi-spark-python' },
    { rule: /\.r$/i, logo: 'fi-r' },
    { rule: /\.txt$/i, logo: 'fi-txt' },
    { rule: /\.log$/i, logo: 'fi-log' },
    { rule: /\.xls$/i, logo: 'fi-xls' },
    { rule: /\.xlsx$/i, logo: 'fi-xlsx' },
    { rule: /\.csv$/i, logo: 'fi-csv' },
    { rule: /\.jar$/i, logo: 'fi-jar' },
    { rule: /\.(tisql)$/i, logo: 'fi-spark' },
    { rule: /\.tiscala$/i, logo: 'fi-scala' },
    { rule: /\.tipyspark$/i, logo: 'fi-spark-python' }
]
